texto1 = "28/11 , P01 -Projeto atrasou a entrega do desenvolvimento em 18 dias, impactando diretamente a fase de testes integrados. Assunto escalado com os gerentes e diretores, pois a data de implantação está completamente comprometida., I01- 18 dias., R01 - GD, , 22/11 , P01- Projeto atrasou a entrega de desenvolvimento em 15 dias, impactando o inicio de testes integrados e comprometendo toda a homologação e implantação planejada para 13/12. Assunto escalado para os gerentes e diretores. , I01 - 8 dias, R01 - GD, , 10/11 , P01- Projeto atrasou a entrega de desenvolvimento em 8 dias impactando o inicio de testes integrados. Assunto escalado para os gerentes e diretória. , I01 - 8 dias, R01 - GD, , 08/11, P01 - Projeto atrasado para inicio da fase de testes integrados, LT SKY não aprovou a entrega do código em dev. (smoke testes) e solicitou novas correções para fábrica.  , I01 - 7 dias  , R01 - GD., , 31/10, P01 - Projeto atraso a entrega de codificação (iCare Campo e Clientes), por baixa qualidade, pois o  recurso da fábrica não tem conhecimento adequada/ necessário para desenvolver. , I01 - 55 dias  (12 dias de atraso apos o replanejamento), R01 - GD., , 24/10, P01 - Projeto com duas frentes de codificação (iCare Campo e Clientes). Estamos com a documentação( ET) e desenvolvimento do  iCare Campo reprovado com baixa qualidade, pois o  recurso da fábrica não tem conhecimento adequada/ necessário para desenvolver. , I01 - 50 dias  (7 dias de atraso apos o replanejamento), R01 - GD., , 17/10, P01 - Projeto com duas frentes de codificação (iCare Campo e Clientes). Estamos com a documentação( ET) e desenvolvimento do  iCare Campo reprovado com baixa qualidade, pois o  recurso da fábrica não tem conhecimento adequada/ necessário para desenvolver. , I01 - 45 dias, R01 - GD."
texto2 = "06/12, P01 - Testes integrados em atraso iniciado em 25/11 ao invés de 27/10. Atraso devido aos impactos na entrega do desenvolvimento pela fábrica, com isso a data de GO-LIVE de 13/12 não tem como ser recuperada,., I01- 18 dias., R01 - Fábrica TM, , 28/11 , P01 -Projeto atrasou a entrega do desenvolvimento em 18 dias, impactando diretamente a fase de testes integrados. Assunto escalado com os gerentes e diretores, pois a data de implantação está completamente comprometida., I01- 18 dias., R01 - GD, , 22/11 , P01- Projeto atrasou a entrega de desenvolvimento em 15 dias, impactando o inicio de testes integrados e comprometendo toda a homologação e implantação planejada para 13/12. Assunto escalado para os gerentes e diretores. , I01 - 8 dias, R01 - GD, , 10/11 , P01- Projeto atrasou a entrega de desenvolvimento em 8 dias impactando o inicio de testes integrados. Assunto escalado para os gerentes e diretória. , I01 - 8 dias, R01 - GD, , 08/11, P01 - Projeto atrasado para inicio da fase de testes integrados, LT SKY não aprovou a entrega do código em dev. (smoke testes) e solicitou novas correções para fábrica.  , I01 - 7 dias  , R01 - GD., , 31/10, P01 - Projeto atraso a entrega de codificação (iCare Campo e Clientes), por baixa qualidade, pois o  recurso da fábrica não tem conhecimento adequada/ necessário para desenvolver. , I01 - 55 dias  (12 dias de atraso apos o replanejamento), R01 - GD., , 24/10, P01 - Projeto com duas frentes de codificação (iCare Campo e Clientes). Estamos com a documentação( ET) e desenvolvimento do  iCare Campo reprovado com baixa qualidade, pois o  recurso da fábrica não tem conhecimento adequada/ necessário para desenvolver. , I01 - 50 dias  (7 dias de atraso apos o replanejamento), R01 - GD."


pesquisar = texto1[:10]

fim = texto2.find(pesquisar)

parte_nova = texto2[:fim]

print (parte_nova)
